/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package production;

import request.sales.*;
import connection.connection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableCellEditor;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reports.SalesReportGenerator;  // Perubahan import
import reports.SimpleReportViewer;    // Import untuk alternatif
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author Lenovo
 */
public class dashboard_request_sales extends javax.swing.JPanel {
    private String usernameLogin;
    

    /**
     * Creates new form dashboard
     */
    public dashboard_request_sales(String username, javax.swing.JPanel utama) {
        initComponents();
        this.usernameLogin = username;
        this.utama = utama;
        table();
    }
    private javax.swing.JPanel utama;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_sales = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/box.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel1.setText("Request Sales Overview");

        table_sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_sales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addContainerGap(759, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        try {
            // Coba cek apakah JasperReport tersedia
            Class.forName("net.sf.jasperreports.engine.JasperReport");
            
            // Jika berhasil, tampilkan laporan dengan JasperReports
            SalesReportGenerator reportGenerator = new SalesReportGenerator();
            reportGenerator.showSalesReport();
            
        } catch (ClassNotFoundException e) {
            // JasperReport tidak tersedia, tampilkan pesan dan gunakan SimpleReportViewer
            int option = JOptionPane.showConfirmDialog(this,
                "Library JasperReports tidak ditemukan. Gunakan tampilan laporan sederhana?",
                "Library Tidak Tersedia",
                JOptionPane.YES_NO_OPTION);
            
            if (option == JOptionPane.YES_OPTION) {
                // Gunakan alternatif SimpleReportViewer
                SimpleReportViewer.showReport();
            } else {
                // Tampilkan petunjuk instalasi
                JOptionPane.showMessageDialog(this,
                    "Silakan instal library JasperReports terlebih dahulu.\n" +
                    "Lihat panduan di file INSTALL_JASPERREPORTS.md",
                    "Instalasi Library",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            // Error lain, tampilkan error dan gunakan SimpleReportViewer
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage() + "\nMenggunakan tampilan laporan sederhana.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            
            SimpleReportViewer.showReport();
        }
    }//GEN-LAST:event_btn_laporanActionPerformed

    public void table() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("No Sales");
        table.addColumn("Waktu");
        table.addColumn("Deskripsi");
        table.addColumn("Operator");
        table.addColumn("Tujuan");
        table.addColumn("Kuantiti");
        table.addColumn("Harga");
        table.addColumn("Diskon");
        table.addColumn("Total Harga");
        table.addColumn("Status");
        table.addColumn("Aksi");
        
        table_sales.setModel(table);
        
        // Set tinggi baris
        table_sales.setRowHeight(35);
        
        // Set lebar kolom Aksi
        table_sales.getColumnModel().getColumn(10).setPreferredWidth(200);
        
        Connection conn = new connection().connect();
        if (conn == null) {
            System.out.println("Koneksi ke database gagal!");
            return;
        }

        try {
            String sql = "SELECT s.no_sales, s.date, s.deskripsi, u.name AS operator_name, p.name AS partner_name, s.qty, s.price, s.discount, s.total, s.status " +
                 "FROM tb_sales_request AS s " +
                 "LEFT JOIN tb_users AS u ON s.id_operator = u.id " +
                 "LEFT JOIN tb_partner AS p ON s.id_partner = p.id";

            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String noSales = rs.getString("no_sales");
                Object status = rs.getObject("status");
                String statusText;
                
                if (status == null) {
                    statusText = "Menunggu Persetujuan";
                } else {
                    boolean statusBool = rs.getBoolean("status");
                    statusText = statusBool ? "Diterima" : "Ditolak";
                }
                
                Object[] row = {
                    noSales,       
                    rs.getString("date"),          
                    rs.getString("deskripsi"),     
                    rs.getString("operator_name"), 
                    rs.getString("partner_name"),    
                    rs.getInt("qty"),              
                    rs.getDouble("price"),         
                    rs.getDouble("discount"),      
                    rs.getDouble("total"),
                    statusText,
                    "Aksi"
                };
                table.addRow(row);
            }

            // Set custom renderer untuk kolom Aksi
            table_sales.getColumnModel().getColumn(10).setCellRenderer(new ButtonRenderer());
            table_sales.getColumnModel().getColumn(10).setCellEditor(new ButtonEditor(this));

        } catch (SQLException e) {
            System.out.println("Error saat mengambil data dari database: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public void updateStatus(String noSales, boolean status) {
        try {
            Connection conn = new connection().connect();
            if (conn != null) {
                String sql = "UPDATE tb_sales_request SET status = ? WHERE no_sales = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setBoolean(1, status);
                pstmt.setString(2, noSales);
                
                int result = pstmt.executeUpdate();
                if (result > 0) {
                    JOptionPane.showMessageDialog(this, 
                        "Status berhasil diubah menjadi " + (status ? "Diterima" : "Ditolak"));
                    table(); // Refresh tabel
                }
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error mengubah status: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_sales;
    // End of variables declaration//GEN-END:variables
}

class ButtonRenderer implements TableCellRenderer {
    private JPanel panel;
    private JButton terimaButton;
    private JButton tolakButton;

    public ButtonRenderer() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 0));
        
        terimaButton = new JButton("Terima");
        tolakButton = new JButton("Tolak");
        
        // Styling tombol Terima
        terimaButton.setBackground(new Color(40, 167, 69));
        terimaButton.setForeground(Color.WHITE);
        terimaButton.setFocusPainted(false);
        terimaButton.setPreferredSize(new Dimension(80, 30));
        terimaButton.setFont(new Font("Arial", Font.BOLD, 12));
        
        // Styling tombol Tolak
        tolakButton.setBackground(new Color(220, 53, 69));
        tolakButton.setForeground(Color.WHITE);
        tolakButton.setFocusPainted(false);
        tolakButton.setPreferredSize(new Dimension(80, 30));
        tolakButton.setFont(new Font("Arial", Font.BOLD, 12));
        
        panel.add(terimaButton);
        panel.add(tolakButton);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        return panel;
    }
}

class ButtonEditor extends DefaultCellEditor {
    private JPanel panel;
    private JButton terimaButton;
    private JButton tolakButton;
    private String noSales;
    private dashboard_request_sales parent;
    private boolean isPushed;

    public ButtonEditor(dashboard_request_sales parent) {
        super(new JCheckBox());
        this.parent = parent;
        
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 0));
        
        terimaButton = new JButton("Terima");
        tolakButton = new JButton("Tolak");
        
        // Styling tombol Terima
        terimaButton.setBackground(new Color(40, 167, 69));
        terimaButton.setForeground(Color.WHITE);
        terimaButton.setFocusPainted(false);
        terimaButton.setPreferredSize(new Dimension(80, 30));
        terimaButton.setFont(new Font("Arial", Font.BOLD, 12));
        
        // Styling tombol Tolak
        tolakButton.setBackground(new Color(220, 53, 69));
        tolakButton.setForeground(Color.WHITE);
        tolakButton.setFocusPainted(false);
        tolakButton.setPreferredSize(new Dimension(80, 30));
        tolakButton.setFont(new Font("Arial", Font.BOLD, 12));
        
        terimaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                parent.updateStatus(noSales, true);
            }
        });
        
        tolakButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                parent.updateStatus(noSales, false);
            }
        });
        
        panel.add(terimaButton);
        panel.add(tolakButton);
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
        noSales = table.getValueAt(row, 0).toString();
        isPushed = true;
        return panel;
    }

    @Override
    public Object getCellEditorValue() {
        isPushed = false;
        return "Aksi";
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }
}
