/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import stock_management.*;
import java.awt.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import partner.index_partner;
import request.production.form_production_request;
import request.sales.form_sales_request;
import user.index1;

/**
 *
 * @author Lenovo
 */
public class dashboard extends javax.swing.JFrame {
    private String usernameLogin;

    /**
     * Creates new form index
     */
    public dashboard(String username) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.usernameLogin = username;
        
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        sidebar.setBackground(new java.awt.Color(0, 0, 102));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 923));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(21, 25, 36));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        content.setBackground(new java.awt.Color(255, 102, 102));

        utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1795, 962));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        utama.add(new index1(usernameLogin));
        utama.repaint();
        utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard("default").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables

    private void addMenu(item... menu) {
        for (int i = 0; i < menu.length; i++) {
            pn_menu.add(menu[i]);
            ArrayList<item> subMenu = menu[i].getSubMenu();
            for (item m : subMenu) {
                addMenu (m);
            }
        }
        pn_menu.revalidate();
    }

    private void execute() {
        ImageIcon iconStockManagement = new ImageIcon(getClass().getResource("/assets/img/stock_management.png"));
        ImageIcon iconRequest = new ImageIcon(getClass().getResource("/assets/img/list.png"));
        ImageIcon iconProduction = new ImageIcon(getClass().getResource("/assets/img/production.png"));
        ImageIcon iconSku= new ImageIcon(getClass().getResource("/assets/img/production.png"));
        ImageIcon iconPartner= new ImageIcon(getClass().getResource("/assets/img/production.png"));
        
        ImageIcon iconStock = new ImageIcon(getClass().getResource("/assets/img/stock.png"));

        
//        item stock = new item(null, true, iconStock, "Production", null);

        item createRequest = new item(null, true, iconRequest, "Sales Request", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                utama.removeAll();
                utama.add(new request.sales.dashboard(usernameLogin, utama));
                utama.repaint();
                utama.revalidate();
            }
        });
        
        item productionRequest = new item(null, true, iconRequest, "Production Request", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                utama.removeAll();
                utama.add(new request.production.dashboard(usernameLogin, utama));
                utama.repaint();
                utama.revalidate();
            }
        });
        
        item accRequestSales = new item(null, true, iconRequest, "Sales Request", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                utama.removeAll();
                utama.add(new production.dashboard_request_sales(usernameLogin, utama));
                utama.repaint();
                utama.revalidate();
            }
        });
        
        item accRequestProduction = new item(null, true, iconRequest, "Production Request", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                utama.removeAll();
                utama.add(new production.dashboard_request_production(usernameLogin, utama));
                utama.repaint();
                utama.revalidate();
            }
        });
        
        item stockManagement = new item(iconStockManagement, false, null, "Dashboard", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                utama.removeAll();
                utama.add(new index1(usernameLogin));
                utama.repaint();
                utama.revalidate();
            }
        }); 
        item request = new item(iconRequest, false, null, "Request", null, createRequest, productionRequest); 
        item production = new item(iconProduction, false, null, "Production", null,accRequestSales, accRequestProduction); 
        item sku = new item(iconSku, false, null, "SKU", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                utama.removeAll();
                utama.add(new sku.DashboardSku(utama));
                utama.repaint();
                utama.revalidate();
            }
        }); 
        item partner = new item(iconPartner, false, null, "Partner", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                utama.removeAll();
                utama.add(new partner.dashboard_partner(utama));
                utama.repaint();
                utama.revalidate();
            }
        }); 
        
        item user = new item(iconPartner, false, null, "Management User", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                utama.removeAll();
                utama.add(new user.dashboard_user(utama));
                utama.repaint();
                utama.revalidate();
            }
        }); 
         
        
        addMenu(stockManagement, request, production, sku, partner, user);
    }
}
